sudo: required
language: bash
services:
  - docker
before_script:
  - export APP_IMAGE=keboola-python-transformation-v2
  - docker build . --tag=$APP_IMAGE
script:
  - docker-compose run --rm --entrypoint python dev -m unittest tests/transformationTest.py
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
