variables:
  - name: isTaggedBuild
    value: ${{ startsWith(variables['Build.SourceBranch'],'refs/tags/') }}
  - name: imageTag
    value: ${{ replace(variables['Build.SourceBranch'],'refs/tags/','') }}
  - name: azureContainerRegistry
    value: Keboola ACR

pr: none
trigger:
  # Build is triggered only in branches except master
  # It servers for development, in Azure DevOps is configured Release pipeline triggered by change of base image
  branches:
    include: ['*']
    exclude: ['master']
  tags:
    include: [ '*' ]

pool:
  vmImage: ubuntu-latest

jobs:
  - template: azure-pipelines/jobs/build-transformation-image.yml
    parameters:
      displayName: Build Python Transformation
      componentName: python-transformation-v2
      baseImageTagPrefix: python-3.10-

  - template: azure-pipelines/jobs/build-transformation-image.yml
    parameters:
      displayName: Build Snowpark Transformation
      componentName: python-snowpark-transformation
      baseImageTagPrefix:
