version: '3'
services:
  python-transformation-v2: &main
    build: .
    image: keboola/python-transformation-v2
    user: www-data
    tty: true
    stdin_open: true

  dev:
    <<: *main
    command: bash
    volumes:
      - ./:/code
      - ./data:/data
