version: '3'
services:
  app: &main
    build: .
    image: keboola/python-transformation-v2
    user: www-data
    tty: true
    stdin_open: true
    command: bash
  dev:
    <<: *main
    volumes:
      - ./:/code
      - ./data:/data