version: '3'
services:
  app: &main
    build:
      context: .
      dockerfile: build/Dockerfile
    image: keboola/python-transformation-v2
    user: www-data
    tty: true
    stdin_open: true
  dev:
    <<: *main
    command: bash
    volumes:
      - ./:/code
      - ./data:/data
