parameters:
  - name: displayName
    type: string

  - name: componentName
    type: string

  - name: baseImageTagPrefix
    type: string

jobs:
  - job:
    displayName: ${{ parameters.displayName }}
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: '188d0476-74e5-44c1-85af-bb2689f015f3'
          definition: '16'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          targetPath: '$(Build.SourcesDirectory)'

      - script: |
          set -Eeuo pipefail
          if [[ -z ${BASE_TAG} ]] ; then
            BASE_TAG=$(cat keboola.docker-custom-python.latest-build/base-python-artifact)
          fi
          echo "Base Tag: $BASE_TAG"

          echo "##vso[task.setvariable variable=BASE_TAG]$BASE_TAG"
        displayName: Resolve Latest Tag

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: $(azureContainerRegistry)

      - script: docker-compose build --build-arg BASE_IMAGE_TAG=${{ parameters.baseImageTagPrefix }}$(BASE_TAG) ${{ parameters.componentName }}
        displayName: Build

      - script: docker-compose run --rm ${{ parameters.componentName }} /home/default/bin/python -m unittest tests/transformationTest.py tests/pipConfigTest.py
        displayName: Run tests

      - script: |
          docker tag keboola/${{ parameters.componentName }} keboola.azurecr.io/${{ parameters.componentName }}:latest
          docker tag keboola/${{ parameters.componentName }} keboola.azurecr.io/${{ parameters.componentName }}:$(imageTag)
          docker push -a keboola.azurecr.io/${{ parameters.componentName }}
        condition: and(succeeded(), eq(variables['isTaggedBuild'], 'true'))
        displayName: Push to ACR

      - script: ./deploy.sh
        env:
          KBC_DEVELOPERPORTAL_PASSWORD: $(KBC_DEVELOPERPORTAL_PASSWORD)
          KBC_DEVELOPERPORTAL_USERNAME: $(KBC_DEVELOPERPORTAL_USERNAME)
          KBC_DEVELOPERPORTAL_VENDOR: $(KBC_DEVELOPERPORTAL_VENDOR)
          KBC_DEVELOPERPORTAL_APP: keboola.${{ parameters.componentName }}
          APP_IMAGE: keboola.azurecr.io/${{ parameters.componentName }}
          APP_TAG: $(imageTag)
        condition: and(succeeded(), eq(variables['isTaggedBuild'], 'true'))
        displayName: Deploy to Dev Portal
